### Run command
GET 127.0.0.1:8787/run/command/Turn_off_Lamp
Authorization: Bearer some_test_token

### Run command 2
GET 127.0.0.1:8787/run/command/Turn_on_Lamp
Authorization: Bearer some_test_token

### Groups
GET 127.0.0.1:8787/controls
###
